Add live activities for download progress
kiwix/kiwix-apple pull request #1058
Opened 2024-12-21 22:18 UTC by plyght

Fixes #1037

Add Live Activities support for displaying download progress on the lock screen and in the Dynamic Island.

* Import `ActivityKit` and create a new `DownloadActivityAttributes` struct in `App/App_iOS.swift`.
* Update `Model/DownloadService.swift` to manage Live Activities during download progress changes.
* Modify `Views/BuildingBlocks/DownloadTaskCell.swift` to include Live Activities updates.
* Update `Views/Library/ZimFileDetail.swift` to handle Live Activities for download details.
* Add Live Activities updates in `Views/Library/ZimFilesDownloads.swift`.
* Add a new setting to enable or disable Live Activities in `Views/Settings/Settings.swift`.
* Handle alerts for Live Activities in `Views/ViewModifiers/AlertHandler.swift`.
* Add `Model/DownloadActivityAttributes.swift` to define the attributes for Live Activities.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/kiwix/kiwix-apple/issues/1037?shareId=XXXX-XXXX-XXXX-XXXX).

2024-12-22 05:56 UTC, kelson42 commented
@plyght Thank you for your PR, we will review it, but might take a while considering we are now mostly in the Christmas break.

2024-12-22 05:57 UTC, plyght commented
> we are now mostly in the Christmas break.

@kelson42 All good! Have a wonderful Christmas!

2024-12-30 14:14 UTC, rgaudin commented
@plyght thank you for your PR.

- Please don't remove file headers.
- Doesn't compile on my machine
- Doesn't compile on CI
- There are a couple of codefactor issues that can be addressed once the code actually runs.

2024-12-30 14:14 UTC, rgaudin requested changes
@plyght thank you for your PR.

- Please don't remove file headers.
- Doesn't compile on my machine
- Doesn't compile on CI
- There are a couple of codefactor issues that can be addressed once the code actually runs.

2025-01-02 22:44 UTC, BPerlakiH commented
Thank you for your PR @plyght .

By the first glance, it needs more work.
I can come back to this later. Some first observations:
- the imported [ActivityKit](https://developer.apple.com/documentation/activitykit) is only available for iOS and only from 16.1. We do use the same code base for both macOS min. 13.0, and iOS min. 15.
- the framework import should be added to project.yml, since we use that for generating our Xcode project. By bet is that is should be: 
```
      - sdk: Activity.framework
        destinationFilters:
          - iOS
```
- for solving the iOS 16.1 issue, it needs to be wrapped in: ``@available(iOS 16.1, *)``
- since our views and most of our view models are re-used for both iOS and macOS, adding this to the views (cells) etc, is not the easiest task, and I would not recommend doing that.
- I think hooking into the `DownloadTasksPublisher` should be more enough to get all the relevant data.
- Another thing to look out, is that we can have multiple downloads running simultaneously.

2025-01-02 22:51 UTC, BPerlakiH commented on Model/DownloadService.swift
> +            let speed = Double(bytesWritten) / 1024.0 / 1024.0 // Convert to MB/s
This seems to be incorrect. 
It has no notion of time, therefore it cannot represent speed, which is **per second**.

2025-01-02 22:53 UTC, BPerlakiH commented on Views/Settings/Settings.swift
> +            Toggle("library_settings.toggle.live_activities".localized, isOn: $enableLiveActivities)
This seems to be a nice addition, but the value of it isn't read anywhere, so it's not turning anything on / off atm.

2025-01-02 23:39 UTC, BPerlakiH commented on App/App_iOS.swift
> +struct DownloadActivityAttributes: ActivityAttributes {
This struct is a duplicate.

2025-01-03 10:16 UTC, BPerlakiH commented
Closing this PR for now, it requires more work, and a more throughout approach to handle cross platform, and iOS 16.1 availability.

2025-01-03 10:16 UTC, closed without merging